//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENoticeBoard
{
    using System;
    using System.Collections.Generic;
    
    public partial class Downtime
    {
        public int DownTimeId { get; set; }
        public string Subject { get; set; }
        public System.DateTime Date { get; set; }
        public string Description { get; set; }
        public int Duration { get; set; }
        public int Type { get; set; }
        public bool isDeleted { get; set; }
        public string Status { get; set; }
    
        public virtual Downtimetype Downtimetype { get; set; }
    }
}
