//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENoticeBoard
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyDatabaseEntities : DbContext
    {
        public MyDatabaseEntities()
            : base("name=MyDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Breakage> Breakages { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<Object> Objects { get; set; }
        public virtual DbSet<Rock> Rocks { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<BreakageType> BreakageTypes { get; set; }
        public virtual DbSet<Downtimetype> Downtimetypes { get; set; }
        public virtual DbSet<Site> Sites { get; set; }
        public virtual DbSet<Vw_ObjectsWithinFinancialPeriod> Vw_ObjectsWithinFinancialPeriod { get; set; }
        public virtual DbSet<Vw_BreakagesWithinFinancialPeriod> Vw_BreakagesWithinFinancialPeriod { get; set; }
        public virtual DbSet<Downtime> Downtimes { get; set; }
        public virtual DbSet<Vw_DowntimesWithinFinancialPeriod> Vw_DowntimesWithinFinancialPeriod { get; set; }
    }
}
