//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENoticeBoard
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_BreakagesWithinFinancialPeriod
    {
        public System.DateTime Date { get; set; }
        public string FinancialPeriod { get; set; }
        public string FinancialYear { get; set; }
        public int BreakageId { get; set; }
        public string Site { get; set; }
        public string Type { get; set; }
        public decimal Cost { get; set; }
        public bool isDeleted { get; set; }
        public string Subject { get; set; }
    }
}
